# Generated by Django 4.2.2 on 2023-06-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_sn_device_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='s',
            new_name='sn',
        ),
    ]
