# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('fw', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('plmn', models.CharField(max_length=100)),
                ('cell', models.IntegerField()),
                ('rf', models.IntegerField()),
                ('gps', models.CharField(max_length=100)),
                ('cnm', models.IntegerField()),
                ('sync', models.CharField(max_length=100)),
                ('rip', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('tmp', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('frqc', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TermInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(max_length=100)),
                ('tmsi', models.CharField(max_length=100)),
                ('tmei', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
            ],
        ),
    ]
