# Generated by Django 4.2.2 on 2023-06-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_device_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='sn',
            new_name='s',
        ),
    ]
