# Generated by Django 4.2.2 on 2023-06-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_alter_device_content_alter_device_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='content',
            field=models.CharField(default=0, max_length=5000),
        ),
        migrations.AlterField(
            model_name='device',
            name='intro',
            field=models.CharField(default=0, max_length=2000),
        ),
    ]
