# Generated by Django 4.2.2 on 2023-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_device_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='content',
            field=models.CharField(default=0, max_length=5000),
        ),
        migrations.AddField(
            model_name='device',
            name='intro',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AlterField(
            model_name='device',
            name='release_time',
            field=models.CharField(max_length=1000),
        ),
    ]
