# Generated by Django 4.2.2 on 2023-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_device_content_device_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('intro', models.CharField(default=0, max_length=2000)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
