# Generated by Django 4.2.2 on 2023-06-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_remove_school_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('intro', models.CharField(default=0, max_length=2000)),
            ],
        ),
    ]
