# Generated by Django 4.2.2 on 2023-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('advice', models.CharField(default=0, max_length=2000)),
            ],
        ),
    ]
