# Generated by Django 4.2.2 on 2023-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_suggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='theme',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
