# Generated by Django 4.2.2 on 2023-06-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_rename_band_device_link_rename_frqc_device_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='release_time',
            field=models.CharField(max_length=1000),
        ),
    ]
