# Generated by Django 4.2.2 on 2023-06-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_device_release_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='release_time',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
