# Generated by Django 4.2.2 on 2023-06-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_remove_device_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='release_time',
            field=models.CharField(max_length=100),
        ),
    ]
