# Generated by Django 4.2.2 on 2023-06-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='rank',
        ),
    ]
